### PR TITLE
Use github actions for docker builds

### PR DESCRIPTION
**Pull request by mainnet-pat**
Hi Calin,

I propose another way of building the multiarch docker image - with github actions instead of docker builder. Not only has it shorter queue times, but also supports the `buildx` scheme. [We use this approach in mainnet since november](https://github.com/mainnet-cash/mainnet-js/blob/efd0993d2d813e7b60ac75ff76ba69de943d97b1/.github/workflows/Publish.yml#L48)
Before merging, you'd need to add a secret to the repository named `DOCKERHUB_PASSWORD` and fill it with your docker hub password.

You can merge it as is, since I already have retargeted it to cculianu/fulcrum.

Cheers,
pat.

### CODE REVIEW

**Comment by mainnet-pat** [comment]
Somehow in the github action, only the amd64 is getting is built and pushed as arm64. Investigating

**Comment by cculianu** [comment]
Do I add the secret to the "repository" or to the "environment"?  There seems to be 2 places you can specify secrets.  Which one do I add it to?  (In this screenshot I added it to both).  

Man this stuff is unnecessarily confusing.  I wish they would be more clear in their built-in help about what is what.


---

Screen Shot 2021-07-03 at 4 29 36 AM

**Comment by mainnet-pat** [comment]
I've added mine in the repository section and it is working.
Also I think I have never seen this env secrets section previously too.

**Comment by cculianu** [comment]
> I've added mine in the repository section and it is working.
> Also I think I have never seen this env secrets section previously too.

Ok, I'll delete the env secrets thing and leave it in the repository.  Let's push this bad-boy and see it working.

**Comment by cculianu** [comment]
Ugh. The github CI action thingie got this error:

```
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c apt-get update -y &&     apt-get install -y software-properties-common &&     add-apt-repository ppa:mainnet-pat/opt-qt-5.13.2-bionic &&     apt-get update -y &&     apt-get install -y qt513base openssl &&     apt-get install -y git build-essential pkg-config zlib1g-dev libbz2-dev libjemalloc-dev libjemalloc1 libzmq3-dev &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*]: exit code: 100
```

Thoughts?

**Comment by mainnet-pat** [comment]
Yes, I was following the build. Trying to wrap my head around this issue.

**Comment by mainnet-pat** [comment]
Mind restarting the build job just for a test?

**Comment by cculianu** [comment]
> Mind restarting the build job just for a test?

I did. Same result.  To its credit it's fast, at least. :)

**Comment by mainnet-pat** [comment]
Not quite the same, now it failed to log in to docker hub

**Comment by mainnet-pat** [comment]
Oops, looked at a wrong browser tab

**Comment by cculianu** [comment]
I.. think I may have fixed it. I googled around and found this needs to be added:

```
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
```

Source: https://github.com/docker/setup-buildx-action

It.. seems to be working so far.

**Comment by mainnet-pat** [comment]
Nicely done! I diverted my research in completely wrong direction it seems!

**Comment by cculianu** [comment]
> Nicely done! I diverted my research in completely wrong direction it seems!

Ha, thanks. I'm amazed how high quality this new github CI actions thing is. It's very fast.  Still waiting for it to complete.. it ain't over until the fat lady sings.  But -- so far it's still building using QEMU.. let's hope it uploads the image correctly.

Assuming it does -- do verify that the uploaded image (esp. the arm64 one) works ok...

**Comment by mainnet-pat** [comment]
Cool! One improvement consideration: since buildx does its both build jobs in parallel, we could reduce the `make` concurrency by a factor of 2. Might speed up the overall process.

**Comment by mainnet-pat** [comment]
> Assuming it does -- do verify that the uploaded image (esp. the arm64 one) works ok...

All is fine. The images produced are of correct architecture and our mainnet regtest harness boots up all good on arm64.
Thanks for being responsive and pulling my changes through quite fast!

**Comment by cculianu** [comment]
> Cool! One improvement consideration: since buildx does its both build jobs in parallel, we could reduce the `make` concurrency by a factor of 2. Might speed up the overall process.

Yeah that occurred to me too.  How do we do that?  I can't think of an easy `bash` expression to do that as a 1-liner e.g. `$(nproc)/2`. Also note that if `nproc` is 1, dividing by 2 leads to 0.

I am ok with it being slower than needed or whatever.  What ends up happening anyway is the amd64 build finishes super fast -- and then the arm64 is left to linger for many minutes.  I think it's fine the way it is, probably.

**Pull request merged**
