### PR TITLE
chore: test build on release

### PR DESCRIPTION
**Pull request by openoms**

### CODE REVIEW

**Comment by cculianu** [comment]
???

**Comment by openoms** [comment]
Opened the PR prematurely. Testing the automatic publishing of the Docker image in my fork.

**Comment by openoms** [comment]
I presume the issue is in how the release is created.

In my fork I have created a tag with:
```
git tag -s v1.9.2-dev && git push origin v1.9.2-dev
```
and added a release in the github web UI using the tag.
This way the Publish action is running:
https://github.com/openoms/Fulcrum/actions/runs/6531526697

@cculianu what is your process for the releases? Would like to help making it trigger the action automatically.

**Comment by cculianu** [comment]
I sometimes tag as you do: `git tag -s -v1.9.2 && git push origin v1.9.2`.

I sometimes use the gitlab UI to "draft a new release" -> assign a new tag that way.

Is the latter way the problem? Does the trigger only work in the first way?

**Comment by openoms** [comment]
>I sometimes use the gitlab UI to "draft a new release" -> assign a new tag that way.
Is the latter way the problem? Does the trigger only work in the first way?

Yes, I think especially if you are using a non github UI the action is not getting triggered because the release is coming through another channel.

Would suggest to use the git cli to make and sign releases.
Thank you for starting the recent ones manually, but it shouldn't be necessary.

Closing this as the solution is likely not to change the Github Action, but the manual release process.

**Pull request closed without merging**
