### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by hegjon**
Added version that documents how to update files that depends on the version

### CODE REVIEW

**Comment by cculianu** [comment]
Would you mind terribly if the `bump-version.sh` script were moved to the `contrib/` folder: I'm trying to keep the top-level as clean from utility scripts as possible.. since I envision many such scripts will eventually exist (with any luck)...

Can you update the PR? Or shall I after merge?

**Comment by cculianu** [comment]
Thanks for the script, by the way. 1 less thing to remember by using it.  Very helpful.

**Comment by hegjon** [comment]
I do not mind that you move it to contrib.

I was thinking if putting it in the contrib folder, but I ended up putting in the root folder because that was the place it lived in at my previous employers.

**Comment by hegjon** [comment]
I would prefer to not need a script like this, but my experince is that there seems that there are alwats some files that needs version hardcoded in them.

**Comment by cculianu** [comment]
Yeah I would prefer it too -- but it's better to have it than forget to update the .spec file.. :)

**Pull request merged**
