### PR TITLE
Build: Add Travis CI configuration for Ubuntu Bionic, macOS and Windows

### PR DESCRIPTION
**Pull request by EchterAgo**
https://travis-ci.org/EchterAgo/Fulcrum/builds/636349578

### CODE REVIEW

**Comment by EchterAgo** [comment]
I think this needs some more work to automatically upload binaries to bintray:

https://docs.travis-ci.com/user/deployment/bintray/

You can even use this to automatically create GitHub releases on a tag for example:

https://docs.travis-ci.com/user/deployment/releases/

**Comment by EchterAgo** [comment]
Updated to simplify and fix the Windows build configuration, which now correctly builds release mode.

**Comment by EchterAgo** [comment]
Build for https://github.com/cculianu/Fulcrum/pull/11/commits/172e42764deaa47bd78af1f67b8a823598e35449 :

https://travis-ci.org/EchterAgo/Fulcrum/builds/636451819

**Comment by cculianu** [comment]
> I think this needs some more work to automatically upload binaries to bintray:
> 
> https://docs.travis-ci.com/user/deployment/bintray/
> 
> You can even use this to automatically create GitHub releases on a tag for example:
> 
> https://docs.travis-ci.com/user/deployment/releases/

That's awesome.. I'll have to do that for first release.. ha! :D

**Pull request merged**
